[package]
name = "fmod-sys"
version = "0.1.0"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
studio=[]

[dependencies]

[build-dependencies]
bindgen = "*"