name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: khonsulabs/build-rust:latest
      options: "--security-opt seccomp=unconfined"

    steps:
      - uses: actions/checkout@v1
      - name: Run tests on stable
        run: cargo test --all-features
        env:
          LD_LIBRARY_PATH: /home/runner/work/fmod-sys/fmod-sys/fmodapi

      - name: Run tests on nightly
        run: cargo test +nightly --all-features
        env:
          LD_LIBRARY_PATH: /home/runner/work/fmod-sys/fmod-sys/fmodapi
