name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: khonsulabs/build-rust:latest
      options: "--security-opt seccomp=unconfined"

    steps:
      - uses: actions/checkout@v1
      - name: Run tests on stable
        run: LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`pwd`/fmodapi/" cargo test --all-features

      - name: Run tests on nightly
        run: LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`pwd`/fmodapi/" cargo test +nightly --all-features
